# Generated by Django 4.0.6 on 2022-07-11 12:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.IntegerField(verbose_name='Длительность')),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flights_destination', to='flights.airport', verbose_name='Место прибытия')),
                ('origin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flights_origin', to='flights.airport', verbose_name='Место отбытия')),
            ],
        ),
    ]
