# Generated by Django 4.0.6 on 2022-07-12 15:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0002_flight'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата создания'),
        ),
    ]
