# Generated by Django 4.0.6 on 2022-07-22 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0003_flight_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Passanger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=60)),
                ('last_name', models.CharField(max_length=60)),
                ('slug', models.SlugField(blank=True, null=True, unique=True, verbose_name='ЧПУ')),
                ('flight', models.ManyToManyField(blank=True, related_name='passangers', to='flights.flight')),
            ],
            options={
                'verbose_name': 'Пассажир',
            },
        ),
    ]
